# This action runs all common tooling for foundry repos
# It does not comment any results though.
# If you want to have comments on your repo, also install comment.yml
name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-lint-prettier.yml@main
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
  debug-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup RPC env
        uses: bgd-labs/action-rpc-env@f56d90aa2505822c6c81a9242625551b68b4859f
        with:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Debug - Run forge coverage directly with FOUNDRY_PROFILE=ci
        run: forge coverage --fuzz-runs 1 --report lcov --no-match-coverage "(test|script|.t.sol|.s.sol|deployment|mock)"
        env:
          FOUNDRY_PROFILE: ci
# only when the repo has zksync code
#  test-zk:
#    uses: bgd-labs/github-workflows/.github/workflows/foundry-test-zk.yml@main
